# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Brik Masonry
email: Brikit@tahighspeed.com
description: We are family owned and operated We do historical building brick and/or stone color matching and repair We are bonded, licensed and insured.
owner: Brik Huntington
phone: +1 417 353 1507
address: PO Box 1842, Nixa, Missouri 65714
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zachdyerdesign.github.io/brickmasonry" # the base hostname & protocol for your site,

# Build settings
markdown: kramdown
